spring.application.name=service-product
server.port=8002
spring.config.import=optional:nacos:common.properties?group=product

spring.cloud.nacos.server-addr=127.0.0.1:18848
spring.cloud.nacos.discovery.username=nacos
spring.cloud.nacos.discovery.password=stVIc1DecAR9
spring.cloud.nacos.config.namespace=test
spring.cloud.nacos.config.username=nacos
spring.cloud.nacos.config.password=stVIc1DecAR9