server:
  port: 8081
spring:
  application:
    name: service-order
  config:
    import: optional:nacos:common.properties?group=order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
        username: nacos
        password: stVIc1DecAR9
      config:
        server-addr: 127.0.0.1:18848
        namespace: test
        username: nacos
        password: stVIc1DecAR9

---
spring:
  config:
    import:
      - optional:nacos:common.properties?group=order
      - optional:nacos:database.properties?group=order
    activate:
      on-profile: dev
---
spring:
  config:
    import:
      - optional:nacos:common.properties?group=order
    activate:
      on-profile: test
---


